AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        prenom:
            type: string
            length: 255
            nullable: true
        codePostal:
            type: string
            length: '5'
        ville:
            type: string
            lenght: 50

